### ISSUE TITLE
Can't scale down large EC2 deployment due to throttling

### ISSUE THREAD

**Issue by mirw** [Metaswitch/chef#179]
Scale down a large (more than about 20 nodes) deployment on EC2.  This fails while updating DNS because "Rate exceeded".

This is because, when preparing to quiesce, we call KnifeDnsRecordsCreate, which spins through every DNS record (even nodes that are staying) and updates them in EC2.  This generates so much load (and has no pacing) that EC2 rejects it.

The fix is probably to pace our requests better, but alternatively, we might not need to do full KnifeDnsRecordsCreate processing, so we might be able to simplify there too.

**Comment by bossmc** [comment]
Fixed by #196

**Comment by eleanor-merry** [comment]
Reopening as I'm still seeing this just on resizing a fairly small deployment

**Comment by eleanor-merry** [comment]
I've tested this again with the new code and I'm no longer seeing this

**Comment by johadalin** [comment]
No sleep timer at the top of the script meant that the DNS requests were reaching the rate limit. 
The fix is to put in sleep(0.2) after requesting a record, rather than only after modifying one, which slows the process down correctly so that it passes through without problems.
